package com.workshop.set.lang;

import com.workshop.set.interfaces.*;

/**
 * The Gensym class implements a symbol generator for generic subclasses S
 * of Symbol. It generates fresh names and unique names that can be compared for
 * equality, on each call to its "generate" method. the Gensym itself can also be
 * compared with equality - two Gensyms are considered equal if they have generated the
 * same number of symbols, thereby being in the same internal state. Symbols from different
 * symbol generators are never considered equal.
 *
 * Each instance of Gensym is considered unique. Therefore, it relies on the default
 * equality comparison, which is true only in the case of reflexivity.
 *
 */
public class NameGenerator
    implements Gensym {
    public class Name implements Symbol, Term {
        private Name( Gensym factory, long index, String hint ) {
            this.readable = hint;
            this.factory = factory;
            this.index = index;
        }

        private final String readable;
        private final Gensym factory;
        private final long index;


        public boolean matches( long index ) { return index == this.index; }
        public boolean matches( Gensym factory ) { return factory.equals(this.factory); }

        public Name create( Gensym factory, long index, String h ) {
            return new Name( factory, index, h );
        }

        /**
         * Two symbols are equal if and only if they were produced by the same
         * symbol factory, and they are indexed by the same de Bruijn number.
         *
         * @param o an object to check this Symbol against
         * @return a boolean indicating whether this and o are equal.
         */
        @Override
        public boolean equals( Object o ) {
            try {
                return ((Name)o).matches( index )
                    && ((Name)o).matches( factory );
            } catch ( ClassCastException _ ) {
                return false;
            }
        }
        @Override
        public String toString() {
            return readable + Long.toString( index );
        }

        @Override
        public Term typesAs( Context gamma ) {
            return null;
        }

        @Override
        public Value evaluatesTo( Environment eta ) {
            return null;
        }
    }

    public NameGenerator() { state = 0L; }

    private long state;

    /**
     * This method generates a fresh, unique symbol, with respect to this
     * Symbol Generator's internal state. Symbols can be compared for equality
     * in constant time.
     *
     * @return a new Symbol as generated by this symbol factory.
     */
    public Name generate() { return new Name( this, state++, "" ); }
    public Name generate( String h ) { return new Name( this, state++, h ); }
}
